// This file is generated by omniidl (C++ backend)- omniORB_4_0. Do not edit.
#ifndef __callreq_hh__
#define __callreq_hh__

#ifndef USE_omniORB_logStream
#define USE_omniORB_logStream
#endif

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_callreq
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_callreq
#endif



#ifndef __commons_hh_EXTERNAL_GUARD__
#define __commons_hh_EXTERNAL_GUARD__
#include <commons.hh>
#endif


#ifdef USE_stub_in_nt_dll
#ifndef USE_core_stub_in_nt_dll
#define USE_core_stub_in_nt_dll
#endif
#ifndef USE_dyn_stub_in_nt_dll
#define USE_dyn_stub_in_nt_dll
#endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE org

_CORBA_MODULE_BEG

  _CORBA_MODULE pgj

  _CORBA_MODULE_BEG

    _CORBA_MODULE corba

    _CORBA_MODULE_BEG

      enum instantiation_type { INSTANTATION_SESSION, INSTANTATION_CALL, INSTANTATION_GLOBAL /*, __max_instantiation_type=0xffffffff */ };
      typedef instantiation_type& instantiation_type_out;

      struct callreq {
        typedef _CORBA_ConstrType_Variable_Var<callreq> _var_type;

        
        CORBA::String_member sid;

        CORBA::String_member classname;

        CORBA::String_member methodname;

        typedef _CORBA_Unbounded_Sequence< type_value_pair >  _values_seq;
        _values_seq values;

        CORBA::Boolean isoneway;

        instantiation_type instantiation;

      

        void operator>>= (cdrStream &) const;
        void operator<<= (cdrStream &);
      };

      typedef callreq::_var_type callreq_var;

      typedef _CORBA_ConstrType_Variable_OUT_arg< callreq,callreq_var > callreq_out;

    _CORBA_MODULE_END

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_org
_CORBA_MODULE_BEG

  _CORBA_MODULE pgj
  _CORBA_MODULE_BEG

    _CORBA_MODULE corba
    _CORBA_MODULE_BEG

    _CORBA_MODULE_END

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

inline void operator >>=(org::pgj::corba::instantiation_type _e, cdrStream& s) {
  ::operator>>=((CORBA::ULong)_e, s);
}

inline void operator <<= (org::pgj::corba::instantiation_type& _e, cdrStream& s) {
  CORBA::ULong _0RL_e;
  ::operator<<=(_0RL_e,s);
  switch (_0RL_e) {
    case org::pgj::corba::INSTANTATION_SESSION:

    case org::pgj::corba::INSTANTATION_CALL:

    case org::pgj::corba::INSTANTATION_GLOBAL:


    _e = (org::pgj::corba::instantiation_type) _0RL_e;
    break;
  default:
    OMNIORB_THROW(MARSHAL,_OMNI_NS(MARSHAL_InvalidEnumValue),
                  (CORBA::CompletionStatus)s.completion());
  }
}





#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_callreq
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_callreq
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_callreq
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_callreq
#endif

#endif  // __callreq_hh__

