/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "workaround.h"

void
org_pgj_corba_CallServer_sendMessage(org_pgj_corba_CallServer _obj,
				     const CORBA_any * message,
				     CORBA_Environment * ev)
{
#ifndef ORBIT_STUB_DEBUG_LOCAL
   if (ORBIT_STUB_IsBypass(_obj, org_pgj_corba_CallServer__classid)) {
      POA_org_pgj_corba_CallServer__epv *_ORBIT_epv;

      ORBIT_STUB_PreCall(_obj);
      _ORBIT_epv =
	 (POA_org_pgj_corba_CallServer__epv *) ORBIT_STUB_GetEpv(_obj,
								 org_pgj_corba_CallServer__classid);
      if (!_ORBIT_epv->sendMessage) {
	 CORBA_exception_set_system(ev, ex_CORBA_NO_IMPLEMENT,
				    CORBA_COMPLETED_NO);
	 return;
      }
      _ORBIT_epv->sendMessage(ORBIT_STUB_GetServant(_obj), message, ev);
      ORBIT_STUB_PostCall(_obj);
   } else
#endif /* ORBIT_STUB_DEBUG_LOCAL */
   {				/* remote marshal */
      gpointer _args[] = {
	 (gpointer) message
      };

      ORBit_small_invoke_stub(_obj,
			      &org_pgj_corba_CallServer__iinterface.methods.
			      _buffer[0], NULL, _args, NULL, ev);

   }
}
CORBA_any *
org_pgj_corba_CallServer_receiveAnsver(org_pgj_corba_CallServer _obj,
				       const CORBA_char * sid,
				       CORBA_Environment * ev)
{
   CORBA_any *_ORBIT_retval;

#ifndef ORBIT_STUB_DEBUG_LOCAL
   if (ORBIT_STUB_IsBypass(_obj, org_pgj_corba_CallServer__classid)) {
      POA_org_pgj_corba_CallServer__epv *_ORBIT_epv;

      ORBIT_STUB_PreCall(_obj);
      _ORBIT_epv =
	 (POA_org_pgj_corba_CallServer__epv *) ORBIT_STUB_GetEpv(_obj,
								 org_pgj_corba_CallServer__classid);
      if (!_ORBIT_epv->receiveAnsver) {
	 CORBA_exception_set_system(ev, ex_CORBA_NO_IMPLEMENT,
				    CORBA_COMPLETED_NO);
	 return _ORBIT_retval;
      }
      _ORBIT_retval =
	 _ORBIT_epv->receiveAnsver(ORBIT_STUB_GetServant(_obj), sid, ev);
      ORBIT_STUB_PostCall(_obj);
   } else
#endif /* ORBIT_STUB_DEBUG_LOCAL */
   {				/* remote marshal */
      gpointer _args[] = {
	 (gpointer) & sid
      };

      ORBit_small_invoke_stub(_obj,
			      &org_pgj_corba_CallServer__iinterface.methods.
			      _buffer[1], &_ORBIT_retval, _args, NULL, ev);

   }
   return _ORBIT_retval;
}

CORBA_any *
org_pgj_corba_CallServer_SendReceive(org_pgj_corba_CallServer _obj,
				     const CORBA_any * message,
				     CORBA_Environment * ev)
{
   CORBA_any *_ORBIT_retval;

#ifndef ORBIT_STUB_DEBUG_LOCAL
   if (ORBIT_STUB_IsBypass(_obj, org_pgj_corba_CallServer__classid)) {
      POA_org_pgj_corba_CallServer__epv *_ORBIT_epv;

      ORBIT_STUB_PreCall(_obj);
      _ORBIT_epv =
	 (POA_org_pgj_corba_CallServer__epv *) ORBIT_STUB_GetEpv(_obj,
								 org_pgj_corba_CallServer__classid);
      if (!_ORBIT_epv->SendReceive) {
	 CORBA_exception_set_system(ev, ex_CORBA_NO_IMPLEMENT,
				    CORBA_COMPLETED_NO);
	 return _ORBIT_retval;
      }
      _ORBIT_retval =
	 _ORBIT_epv->SendReceive(ORBIT_STUB_GetServant(_obj), message, ev);
      ORBIT_STUB_PostCall(_obj);
   } else
#endif /* ORBIT_STUB_DEBUG_LOCAL */
   {				/* remote marshal */
      gpointer _args[] = {
	 (gpointer) message
      };

      ORBit_small_invoke_stub(_obj,
			      &org_pgj_corba_CallServer__iinterface.methods.
			      _buffer[2], &_ORBIT_retval, _args, NULL, ev);

   }
   return _ORBIT_retval;
}
