/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define workaround_COMMON
#include "workaround.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#if ( (TC_IMPL_TC_org_pgj_corba_CallServer_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_CallServer_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_CallServer_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_CallServer_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_CallServer_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_CallServer_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_CallServer_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_CallServer_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_CallServer_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_CallServer_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_CallServer)
#define TC_DEF_TC_org_pgj_corba_CallServer 1
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_CallServer_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_objref,
   0,
   0,
   4,
   0,
   0,
   NULL,
   CORBA_OBJECT_NIL,
   "CallServer",
   "IDL:org/pgj/corba/CallServer:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_char_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_char)
#define TC_DEF_TC_CORBA_sequence_CORBA_char 1
static const CORBA_TypeCode anon_subtypes_array4[] =
   { (CORBA_TypeCode) & TC_CORBA_char_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_char_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array4,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_char_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_char)
#define TC_DEF_TC_CORBA_sequence_CORBA_char 1
static const CORBA_TypeCode anon_subtypes_array11[] =
   { (CORBA_TypeCode) & TC_CORBA_char_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_char_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array11,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_raw_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_raw_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_raw_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_raw_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_raw_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_raw_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_raw_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_raw_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_raw_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_raw_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_raw)
#define TC_DEF_TC_org_pgj_corba_raw 1
static const CORBA_TypeCode anon_subtypes_array14[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_char_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_raw_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_alias,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array14,
   CORBA_OBJECT_NIL,
   "raw",
   "IDL:org/pgj/corba/raw:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_char_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_char)
#define TC_DEF_TC_CORBA_sequence_CORBA_char 1
static const CORBA_TypeCode anon_subtypes_array17[] =
   { (CORBA_TypeCode) & TC_CORBA_char_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_char_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array17,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_type_value_pair_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_type_value_pair_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_type_value_pair_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_type_value_pair_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_type_value_pair_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_type_value_pair_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_type_value_pair_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_type_value_pair_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_type_value_pair_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_type_value_pair_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_type_value_pair)
#define TC_DEF_TC_org_pgj_corba_type_value_pair 1
static const char *anon_subnames_array19[] = { "typename", "value" };
static const CORBA_TypeCode anon_subtypes_array20[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_sequence_CORBA_char_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_type_value_pair_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   2,
   (CORBA_TypeCode *) anon_subtypes_array20,
   CORBA_OBJECT_NIL,
   "type_value_pair",
   "IDL:org/pgj/corba/type_value_pair:1.0",
   (char **) anon_subnames_array19,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_instantiation_type_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_instantiation_type_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_instantiation_type_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_instantiation_type_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_instantiation_type_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_instantiation_type_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_instantiation_type_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_instantiation_type_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_instantiation_type_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_instantiation_type_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_instantiation_type)
#define TC_DEF_TC_org_pgj_corba_instantiation_type 1
static const char *anon_subnames_array22[] =
   { "INSTANTATION_SESSION", "INSTANTATION_CALL", "INSTANTATION_GLOBAL" };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_instantiation_type_struct
   = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_enum,
   0,
   0,
   4,
   0,
   3,
   NULL,
   CORBA_OBJECT_NIL,
   "instantiation_type",
   "IDL:org/pgj/corba/instantiation_type:1.0",
   (char **) anon_subnames_array22,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_pgj_corba_type_value_pair)
#define TC_DEF_TC_CORBA_sequence_org_pgj_corba_type_value_pair 1
static const CORBA_TypeCode anon_subtypes_array26[] =
   { (CORBA_TypeCode) & TC_org_pgj_corba_type_value_pair_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_pgj_corba_type_value_pair_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array26,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_callreq_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_callreq_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_callreq_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_callreq_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_callreq_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_callreq_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_callreq_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_callreq_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_callreq_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_callreq_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_callreq)
#define TC_DEF_TC_org_pgj_corba_callreq 1
static const char *anon_subnames_array28[] =
   { "sid", "classname", "methodname", "values", "isoneway",
"instantiation" };
static const CORBA_TypeCode anon_subtypes_array29[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_string_struct, (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_sequence_org_pgj_corba_type_value_pair_struct, (CORBA_TypeCode) & TC_CORBA_boolean_struct,
(CORBA_TypeCode) & TC_org_pgj_corba_instantiation_type_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_callreq_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   6,
   (CORBA_TypeCode *) anon_subtypes_array29,
   CORBA_OBJECT_NIL,
   "callreq",
   "IDL:org/pgj/corba/callreq:1.0",
   (char **) anon_subnames_array28,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_errorstruct_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_errorstruct_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_errorstruct_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_errorstruct_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_errorstruct_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_errorstruct_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_errorstruct_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_errorstruct_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_errorstruct_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_errorstruct_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_errorstruct)
#define TC_DEF_TC_org_pgj_corba_errorstruct 1
static const char *anon_subnames_array31[] =
   { "sid", "classname", "message", "stacktrace" };
static const CORBA_TypeCode anon_subtypes_array32[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_string_struct, (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_errorstruct_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   4,
   (CORBA_TypeCode *) anon_subtypes_array32,
   CORBA_OBJECT_NIL,
   "errorstruct",
   "IDL:org/pgj/corba/errorstruct:1.0",
   (char **) anon_subnames_array31,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_ex_pgj_error_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_ex_pgj_error)
#define TC_DEF_TC_org_pgj_corba_ex_pgj_error 1
static const char *anon_subnames_array34[] = { "exceptiondata" };
static const CORBA_TypeCode anon_subtypes_array35[] =
   { (CORBA_TypeCode) & TC_org_pgj_corba_errorstruct_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_ex_pgj_error_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_except,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array35,
   CORBA_OBJECT_NIL,
   "ex_pgj_error",
   "IDL:org/pgj/corba/ex_pgj_error:1.0",
   (char **) anon_subnames_array34,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array38[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array38,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_char_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_char)
#define TC_DEF_TC_CORBA_sequence_CORBA_char 1
static const CORBA_TypeCode anon_subtypes_array41[] =
   { (CORBA_TypeCode) & TC_CORBA_char_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_char_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array41,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_sequence_CORBA_char)
#define TC_DEF_TC_CORBA_sequence_CORBA_sequence_CORBA_char 1
static const CORBA_TypeCode anon_subtypes_array44[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_char_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_CORBA_sequence_CORBA_char_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array44,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_char_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_char_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_char)
#define TC_DEF_TC_CORBA_sequence_CORBA_char 1
static const CORBA_TypeCode anon_subtypes_array47[] =
   { (CORBA_TypeCode) & TC_CORBA_char_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_char_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array47,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_sequence_CORBA_char)
#define TC_DEF_TC_CORBA_sequence_CORBA_sequence_CORBA_char 1
static const CORBA_TypeCode anon_subtypes_array50[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_CORBA_char_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_CORBA_sequence_CORBA_char_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array50,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_pgj_corba_raw)
#define TC_DEF_TC_CORBA_sequence_org_pgj_corba_raw 1
static const CORBA_TypeCode anon_subtypes_array53[] =
   { (CORBA_TypeCode) & TC_org_pgj_corba_raw_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_org_pgj_corba_raw_struct
   = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array53,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw)
#define TC_DEF_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw 1
static const CORBA_TypeCode anon_subtypes_array56[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_org_pgj_corba_raw_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array56,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_result_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_result_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_result_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_result_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_result_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_result_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_result_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_result_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_result_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_result_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_result)
#define TC_DEF_TC_org_pgj_corba_result 1
static const char *anon_subnames_array58[] = { "sid", "types", "result_tab" };
static const CORBA_TypeCode anon_subtypes_array59[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_sequence_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_result_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   3,
   (CORBA_TypeCode *) anon_subtypes_array59,
   CORBA_OBJECT_NIL,
   "result",
   "IDL:org/pgj/corba/result:1.0",
   (char **) anon_subnames_array58,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_0 == 'w') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_1 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_2 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_3 == 'k') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_4 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_5 == 'r') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_6 == 'o') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_7 == 'u') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_8 == 'n') \
&& (TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_9 == 'd') \
) && !defined(TC_DEF_TC_CORBA_sequence_org_pgj_corba_type_value_pair)
#define TC_DEF_TC_CORBA_sequence_org_pgj_corba_type_value_pair 1
static const CORBA_TypeCode anon_subtypes_array62[] =
   { (CORBA_TypeCode) & TC_org_pgj_corba_type_value_pair_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct
   TC_CORBA_sequence_org_pgj_corba_type_value_pair_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array62,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_prepared_sql_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_prepared_sql_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_prepared_sql_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_prepared_sql_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_prepared_sql_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_prepared_sql_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_prepared_sql_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_prepared_sql_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_prepared_sql_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_prepared_sql_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_prepared_sql)
#define TC_DEF_TC_org_pgj_corba_prepared_sql 1
static const char *anon_subnames_array64[] = { "statement_id", "data" };
static const CORBA_TypeCode anon_subtypes_array65[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_CORBA_sequence_org_pgj_corba_type_value_pair_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_prepared_sql_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   2,
   (CORBA_TypeCode *) anon_subtypes_array65,
   CORBA_OBJECT_NIL,
   "prepared_sql",
   "IDL:org/pgj/corba/prepared_sql:1.0",
   (char **) anon_subnames_array64,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_simple_sql_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_simple_sql_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_simple_sql_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_simple_sql_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_simple_sql_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_simple_sql_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_simple_sql_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_simple_sql_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_simple_sql_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_simple_sql_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_simple_sql)
#define TC_DEF_TC_org_pgj_corba_simple_sql 1
static const char *anon_subnames_array67[] = { "statement" };
static const CORBA_TypeCode anon_subtypes_array68[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_simple_sql_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array68,
   CORBA_OBJECT_NIL,
   "simple_sql",
   "IDL:org/pgj/corba/simple_sql:1.0",
   (char **) anon_subnames_array67,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_prepare_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_prepare_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_prepare_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_prepare_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_prepare_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_prepare_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_prepare_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_prepare_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_prepare_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_prepare_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_prepare)
#define TC_DEF_TC_org_pgj_corba_prepare 1
static const char *anon_subnames_array70[] = { "statement" };
static const CORBA_TypeCode anon_subtypes_array71[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_prepare_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array71,
   CORBA_OBJECT_NIL,
   "prepare",
   "IDL:org/pgj/corba/prepare:1.0",
   (char **) anon_subnames_array70,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_cursor_close_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_close_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_close_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_close_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_close_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_close_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_close_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_close_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_close_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_close_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_cursor_close)
#define TC_DEF_TC_org_pgj_corba_cursor_close 1
static const char *anon_subnames_array73[] = { "cursorname" };
static const CORBA_TypeCode anon_subtypes_array74[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_cursor_close_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array74,
   CORBA_OBJECT_NIL,
   "cursor_close",
   "IDL:org/pgj/corba/cursor_close:1.0",
   (char **) anon_subnames_array73,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_prep_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_cursor_open_prep)
#define TC_DEF_TC_org_pgj_corba_cursor_open_prep 1
static const char *anon_subnames_array76[] = { "cursorname", "prepared" };
static const CORBA_TypeCode anon_subtypes_array77[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_org_pgj_corba_prepared_sql_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_cursor_open_prep_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   2,
   (CORBA_TypeCode *) anon_subtypes_array77,
   CORBA_OBJECT_NIL,
   "cursor_open_prep",
   "IDL:org/pgj/corba/cursor_open_prep:1.0",
   (char **) anon_subnames_array76,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_open_sql_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_cursor_open_sql)
#define TC_DEF_TC_org_pgj_corba_cursor_open_sql 1
static const char *anon_subnames_array79[] = { "cursorname", "sql" };
static const CORBA_TypeCode anon_subtypes_array80[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_org_pgj_corba_simple_sql_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_cursor_open_sql_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   2,
   (CORBA_TypeCode *) anon_subtypes_array80,
   CORBA_OBJECT_NIL,
   "cursor_open_sql",
   "IDL:org/pgj/corba/cursor_open_sql:1.0",
   (char **) anon_subnames_array79,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_fetch_direction_type_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_fetch_direction_type)
#define TC_DEF_TC_org_pgj_corba_fetch_direction_type 1
static const char *anon_subnames_array82[] =
   { "FETCH_FORWARD", "FETCH_BACKWARD" };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct
   TC_org_pgj_corba_fetch_direction_type_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_enum,
   0,
   0,
   4,
   0,
   2,
   NULL,
   CORBA_OBJECT_NIL,
   "fetch_direction_type",
   "IDL:org/pgj/corba/fetch_direction_type:1.0",
   (char **) anon_subnames_array82,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_org_pgj_corba_cursor_fetch_0 == 'w') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_fetch_1 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_fetch_2 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_fetch_3 == 'k') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_fetch_4 == 'a') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_fetch_5 == 'r') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_fetch_6 == 'o') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_fetch_7 == 'u') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_fetch_8 == 'n') \
&& (TC_IMPL_TC_org_pgj_corba_cursor_fetch_9 == 'd') \
) && !defined(TC_DEF_TC_org_pgj_corba_cursor_fetch)
#define TC_DEF_TC_org_pgj_corba_cursor_fetch 1
static const char *anon_subnames_array85[] =
   { "cursorname", "fetch_direction", "count" };
static const CORBA_TypeCode anon_subtypes_array86[] =
   { (CORBA_TypeCode) & TC_CORBA_string_struct,
(CORBA_TypeCode) & TC_org_pgj_corba_fetch_direction_type_struct, (CORBA_TypeCode) & TC_CORBA_long_struct };
#ifdef ORBIT_IDL_C_IMODULE
static
#endif
const struct CORBA_TypeCode_struct TC_org_pgj_corba_cursor_fetch_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   4,
   0,
   3,
   (CORBA_TypeCode *) anon_subtypes_array86,
   CORBA_OBJECT_NIL,
   "cursor_fetch",
   "IDL:org/pgj/corba/cursor_fetch:1.0",
   (char **) anon_subnames_array85,
   NULL,
   -1,
   0,
   0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE
CORBA_unsigned_long org_pgj_corba_CallServer__classid = 0;
#endif

/* Interface type data */

static ORBit_IArg org_pgj_corba_CallServer_sendMessage__arginfo[] = {
   {TC_CORBA_any, ORBit_I_ARG_IN, "message"},
   {TC_null, 0, NULL}
};
static ORBit_IArg org_pgj_corba_CallServer_receiveAnsver__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "sid"},
   {TC_null, 0, NULL}
};
static ORBit_IArg org_pgj_corba_CallServer_SendReceive__arginfo[] = {
   {TC_CORBA_any, ORBit_I_ARG_IN, "message"},
   {TC_null, 0, NULL}
};

#ifdef ORBIT_IDL_C_IMODULE
static
#endif
ORBit_IMethod org_pgj_corba_CallServer__imethods[] = {
   {
    {2, 2, org_pgj_corba_CallServer_sendMessage__arginfo, FALSE},
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    CORBA_OBJECT_NIL, "sendMessage", 11,
    0 | ORBit_I_METHOD_1_WAY},
   {
    {2, 2, org_pgj_corba_CallServer_receiveAnsver__arginfo, FALSE},
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    TC_CORBA_any, "receiveAnsver", 13,
    0},
   {
    {2, 2, org_pgj_corba_CallServer_SendReceive__arginfo, FALSE},
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    TC_CORBA_any, "SendReceive", 11,
    0},
};
static CORBA_string org_pgj_corba_CallServer__base_itypes[] = {
   "IDL:CORBA/Object:1.0"
};

#ifdef ORBIT_IDL_C_IMODULE
static
#endif
ORBit_IInterface org_pgj_corba_CallServer__iinterface = {
   TC_org_pgj_corba_CallServer, {3, 3, org_pgj_corba_CallServer__imethods,
				 FALSE},
   {1, 1, org_pgj_corba_CallServer__base_itypes, FALSE}
};
