
#include "commons.idl"

module org{
	module pgj{
		module corba{
			
			enum instantiation_type{
				INSTANTATION_SESSION,
				INSTANTATION_CALL,
				INSTANTATION_GLOBAL
			};
			
			struct callreq{
				string sid;
				string classname;
				string methodname;
				sequence<type_value_pair> values;
				boolean isoneway;
				instantiation_type instantiation;
			};
			
		}; 
	};
};
									
