
#include <commons.idl>

module org{
	module pgj{
		module corba{
			
			struct prepared_sql{
				string statement_id;
				sequence <type_value_pair> data;
			};
			
			struct simple_sql{
				string statement;
			};
			
			struct prepare{
				string statement;
			};
			
			struct cursor_close{
				string cursorname;
			};
			
			struct cursor_open_prep{
				string cursorname;
				prepared_sql prepared;
			};
			
			struct cursor_open_sql{
				string cursorname;
				simple_sql sql;
			};
			
			enum fetch_direction_type{
				FETCH_FORWARD,
				FETCH_BACKWARD
			};
			
			struct cursor_fetch{
				string cursorname;
				fetch_direction_type fetch_direction;
				long count;
			};
			
		};
	};
};
