
module org{
	module pgj{
		module corba{
			interface CallServer{
				
				oneway void sendMessage(in any message);
				
				any receiveAnsver(in string sid);
				
				any SendReceive(in any message);
				
			};
		};
	};
};

