// This file is generated by omniidl (C++ backend)- omniORB_4_0. Do not edit.
#ifndef __error_hh__
#define __error_hh__

#ifndef USE_omniORB_logStream
#define USE_omniORB_logStream
#endif

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_error
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_error
#endif





#ifdef USE_stub_in_nt_dll
#ifndef USE_core_stub_in_nt_dll
#define USE_core_stub_in_nt_dll
#endif
#ifndef USE_dyn_stub_in_nt_dll
#define USE_dyn_stub_in_nt_dll
#endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE org

_CORBA_MODULE_BEG

  _CORBA_MODULE pgj

  _CORBA_MODULE_BEG

    _CORBA_MODULE corba

    _CORBA_MODULE_BEG

      struct errorstruct {
        typedef _CORBA_ConstrType_Variable_Var<errorstruct> _var_type;

        
        CORBA::String_member sid;

        CORBA::String_member classname;

        CORBA::String_member message;

        CORBA::String_member stacktrace;

      

        void operator>>= (cdrStream &) const;
        void operator<<= (cdrStream &);
      };

      typedef errorstruct::_var_type errorstruct_var;

      typedef _CORBA_ConstrType_Variable_OUT_arg< errorstruct,errorstruct_var > errorstruct_out;

      class ex_pgj_error : public CORBA::UserException {
      public:
        
        errorstruct exceptiondata;

      

        inline ex_pgj_error() {
          pd_insertToAnyFn    = insertToAnyFn;
          pd_insertToAnyFnNCP = insertToAnyFnNCP;
        }
        ex_pgj_error(const ex_pgj_error&);
        ex_pgj_error(const errorstruct& i_exceptiondata);
        ex_pgj_error& operator=(const ex_pgj_error&);
        virtual ~ex_pgj_error();
        virtual void _raise() const;
        static ex_pgj_error* _downcast(CORBA::Exception*);
        static const ex_pgj_error* _downcast(const CORBA::Exception*);
        static inline ex_pgj_error* _narrow(CORBA::Exception* _e) {
          return _downcast(_e);
        }
        
        void operator>>=(cdrStream&) const ;
        void operator<<=(cdrStream&) ;

        static _core_attr insertExceptionToAny    insertToAnyFn;
        static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

        virtual CORBA::Exception* _NP_duplicate() const;

        static _core_attr const char* _PD_repoId;
        static _core_attr const char* _PD_typeId;

      private:
        virtual const char* _NP_typeId() const;
        virtual const char* _NP_repoId(int*) const;
        virtual void _NP_marshal(cdrStream&) const;
      };

    _CORBA_MODULE_END

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_org
_CORBA_MODULE_BEG

  _CORBA_MODULE pgj
  _CORBA_MODULE_BEG

    _CORBA_MODULE corba
    _CORBA_MODULE_BEG

    _CORBA_MODULE_END

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr





#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_error
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_error
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_error
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_error
#endif

#endif  // __error_hh__

