
#ifndef COMMONS_IDL
#define COMMONS_IDL

module org{
	module pgj{
		module corba{
			typedef sequence<char> raw;
			
			struct type_value_pair{
				string typename;
				boolean isnull;
				raw value;
			};
			
		};
	};
};

#endif

