/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "workaround.h"

void
_ORBIT_skel_small_org_pgj_corba_CallServer_sendMessage
   (POA_org_pgj_corba_CallServer * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    void (*_impl_sendMessage) (PortableServer_Servant _servant,
			       const CORBA_any * message,
			       CORBA_Environment * ev))
{
   _impl_sendMessage(_o_servant, (const CORBA_any *) _o_args[0], _o_ev);
}

void
_ORBIT_skel_small_org_pgj_corba_CallServer_receiveAnsver
   (POA_org_pgj_corba_CallServer * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    CORBA_any * (*_impl_receiveAnsver) (PortableServer_Servant _servant,
					const CORBA_char * sid,
					CORBA_Environment * ev))
{
   *(CORBA_any * *)_o_retval =
      _impl_receiveAnsver(_o_servant, *(const CORBA_char * *) _o_args[0],
			  _o_ev);
}

void
_ORBIT_skel_small_org_pgj_corba_CallServer_SendReceive
   (POA_org_pgj_corba_CallServer * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    CORBA_any * (*_impl_SendReceive) (PortableServer_Servant _servant,
				      const CORBA_any * message,
				      CORBA_Environment * ev))
{
   *(CORBA_any * *)_o_retval =
      _impl_SendReceive(_o_servant, (const CORBA_any *) _o_args[0], _o_ev);
}
static ORBitSmallSkeleton
get_skel_small_org_pgj_corba_CallServer(POA_org_pgj_corba_CallServer *
					servant, const char *opname,
					gpointer * m_data, gpointer * impl)
{
   switch (opname[0]) {
     case 'S':
	if (strcmp((opname + 1), "endReceive"))
	   break;
	*impl =
	   (gpointer) servant->vepv->org_pgj_corba_CallServer_epv->
	   SendReceive;
	*m_data =
	   (gpointer) & org_pgj_corba_CallServer__iinterface.methods.
	   _buffer[2];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_org_pgj_corba_CallServer_SendReceive;
	break;
     case 'r':
	if (strcmp((opname + 1), "eceiveAnsver"))
	   break;
	*impl =
	   (gpointer) servant->vepv->org_pgj_corba_CallServer_epv->
	   receiveAnsver;
	*m_data =
	   (gpointer) & org_pgj_corba_CallServer__iinterface.methods.
	   _buffer[1];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_org_pgj_corba_CallServer_receiveAnsver;
	break;
     case 's':
	if (strcmp((opname + 1), "endMessage"))
	   break;
	*impl =
	   (gpointer) servant->vepv->org_pgj_corba_CallServer_epv->
	   sendMessage;
	*m_data =
	   (gpointer) & org_pgj_corba_CallServer__iinterface.methods.
	   _buffer[0];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_org_pgj_corba_CallServer_sendMessage;
	break;
     default:
	break;
   }
   return NULL;
}

void
POA_org_pgj_corba_CallServer__init(PortableServer_Servant servant,
				   CORBA_Environment * env)
{
   static PortableServer_ClassInfo class_info =
      { NULL,
(ORBit_small_impl_finder) & get_skel_small_org_pgj_corba_CallServer, "IDL:org/pgj/corba/CallServer:1.0",
&org_pgj_corba_CallServer__classid, NULL, &org_pgj_corba_CallServer__iinterface };
   POA_org_pgj_corba_CallServer__vepv *fakevepv = NULL;

   if (((PortableServer_ServantBase *) servant)->vepv[0]->finalize == 0) {
      ((PortableServer_ServantBase *) servant)->vepv[0]->finalize =
	 POA_org_pgj_corba_CallServer__fini;
   }
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   ORBit_classinfo_register(&class_info);
   ORBIT_SERVANT_SET_CLASSINFO(servant, &class_info);

   if (!class_info.vepvmap) {
      class_info.vepvmap =
	 g_new0(ORBit_VepvIdx, org_pgj_corba_CallServer__classid + 1);
      class_info.vepvmap[org_pgj_corba_CallServer__classid] =
	 (((char *) &(fakevepv->org_pgj_corba_CallServer_epv)) -
	  ((char *) (fakevepv))) / sizeof(GFunc);
   }
}

void
POA_org_pgj_corba_CallServer__fini(PortableServer_Servant servant,
				   CORBA_Environment * env)
{
   PortableServer_ServantBase__fini(servant, env);
}
