/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pgj_chanells_corba_CORBAChanellWorker */

#ifndef _Included_org_pgj_chanells_corba_CORBAChanellWorker
#define _Included_org_pgj_chanells_corba_CORBAChanellWorker
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: threadInitNumber */
/* Inaccessible static: stopThreadPermission */
#undef org_pgj_chanells_corba_CORBAChanellWorker_MIN_PRIORITY
#define org_pgj_chanells_corba_CORBAChanellWorker_MIN_PRIORITY 1L
#undef org_pgj_chanells_corba_CORBAChanellWorker_NORM_PRIORITY
#define org_pgj_chanells_corba_CORBAChanellWorker_NORM_PRIORITY 5L
#undef org_pgj_chanells_corba_CORBAChanellWorker_MAX_PRIORITY
#define org_pgj_chanells_corba_CORBAChanellWorker_MAX_PRIORITY 10L
/*
 * Class:     org_pgj_chanells_corba_CORBAChanellWorker
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pgj_chanells_corba_CORBAChanellWorker_run
  (JNIEnv *, jobject);

/*
 * Class:     org_pgj_chanells_corba_CORBAChanellWorker
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pgj_chanells_corba_CORBAChanellWorker_terminate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
