/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#ifndef workaround_H
#define workaround_H 1
#include <glib.h>
#define ORBIT_IDL_SERIAL 19
#include <orbit/orbit-types.h>

#ifdef __cplusplus
extern "C"
{
#endif				/* __cplusplus */

/** typedefs **/
#if !defined(ORBIT_DECL_org_pgj_corba_CallServer) && !defined(_org_pgj_corba_CallServer_defined)
#define ORBIT_DECL_org_pgj_corba_CallServer 1
#define _org_pgj_corba_CallServer_defined 1
#define org_pgj_corba_CallServer__freekids CORBA_Object__freekids
   typedef CORBA_Object org_pgj_corba_CallServer;
   extern CORBA_unsigned_long org_pgj_corba_CallServer__classid;
#if !defined(TC_IMPL_TC_org_pgj_corba_CallServer_0)
#define TC_IMPL_TC_org_pgj_corba_CallServer_0 'w'
#define TC_IMPL_TC_org_pgj_corba_CallServer_1 'o'
#define TC_IMPL_TC_org_pgj_corba_CallServer_2 'r'
#define TC_IMPL_TC_org_pgj_corba_CallServer_3 'k'
#define TC_IMPL_TC_org_pgj_corba_CallServer_4 'a'
#define TC_IMPL_TC_org_pgj_corba_CallServer_5 'r'
#define TC_IMPL_TC_org_pgj_corba_CallServer_6 'o'
#define TC_IMPL_TC_org_pgj_corba_CallServer_7 'u'
#define TC_IMPL_TC_org_pgj_corba_CallServer_8 'n'
#define TC_IMPL_TC_org_pgj_corba_CallServer_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_CallServer_struct;
#define TC_org_pgj_corba_CallServer ((CORBA_TypeCode)&TC_org_pgj_corba_CallServer_struct)
#endif
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_char)
#define ORBIT_DECL_CORBA_sequence_CORBA_char 1
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_0 'w'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_1 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_2 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_3 'k'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_4 'a'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_5 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_6 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_7 'u'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_8 'n'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_9 'd'
#if !defined(_CORBA_sequence_CORBA_char_defined)
#define _CORBA_sequence_CORBA_char_defined 1
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      CORBA_char *_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_CORBA_char;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_char_0)
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_0 'w'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_1 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_2 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_3 'k'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_4 'a'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_5 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_6 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_7 'u'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_8 'n'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_CORBA_char_struct;
#define TC_CORBA_sequence_CORBA_char ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_char_struct)
#endif
#define CORBA_sequence_CORBA_char__alloc() ((CORBA_sequence_CORBA_char *)ORBit_small_alloc (TC_CORBA_sequence_CORBA_char))
#define CORBA_sequence_CORBA_char__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_CORBA_char,(m),(d))
#define CORBA_sequence_CORBA_char_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_char, (l))
#define CORBA_sequence_CORBA_char_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_char, (l))
#endif
#if !defined(_org_pgj_corba_raw_defined)
#define _org_pgj_corba_raw_defined 1
   typedef CORBA_sequence_CORBA_char org_pgj_corba_raw;
#define org_pgj_corba_raw_marshal(x,y,z) CORBA_sequence_CORBA_char_marshal((x),(y),(z))
#define org_pgj_corba_raw_demarshal(x,y,z,i) CORBA_sequence_CORBA_char_demarshal((x),(y),(z),(i))
#if !defined(TC_IMPL_TC_org_pgj_corba_raw_0)
#define TC_IMPL_TC_org_pgj_corba_raw_0 'w'
#define TC_IMPL_TC_org_pgj_corba_raw_1 'o'
#define TC_IMPL_TC_org_pgj_corba_raw_2 'r'
#define TC_IMPL_TC_org_pgj_corba_raw_3 'k'
#define TC_IMPL_TC_org_pgj_corba_raw_4 'a'
#define TC_IMPL_TC_org_pgj_corba_raw_5 'r'
#define TC_IMPL_TC_org_pgj_corba_raw_6 'o'
#define TC_IMPL_TC_org_pgj_corba_raw_7 'u'
#define TC_IMPL_TC_org_pgj_corba_raw_8 'n'
#define TC_IMPL_TC_org_pgj_corba_raw_9 'd'
   extern const struct CORBA_TypeCode_struct TC_org_pgj_corba_raw_struct;
#define TC_org_pgj_corba_raw ((CORBA_TypeCode)&TC_org_pgj_corba_raw_struct)
#endif
#define org_pgj_corba_raw__alloc() ((org_pgj_corba_raw *)ORBit_small_alloc (TC_CORBA_sequence_CORBA_char))
#define org_pgj_corba_raw__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_CORBA_char,(m),(d))
#define org_pgj_corba_raw_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_char, (l))
#endif
#if !defined(_org_pgj_corba_type_value_pair_defined)
#define _org_pgj_corba_type_value_pair_defined 1
   typedef struct org_pgj_corba_type_value_pair_type
      org_pgj_corba_type_value_pair;
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_char)
#define ORBIT_DECL_CORBA_sequence_CORBA_char 1
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_0 'w'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_1 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_2 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_3 'k'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_4 'a'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_5 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_6 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_7 'u'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_8 'n'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_9 'd'
#if !defined(_CORBA_sequence_CORBA_char_defined)
#define _CORBA_sequence_CORBA_char_defined 1
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      CORBA_char *_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_CORBA_char;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_char_0)
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_0 'w'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_1 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_2 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_3 'k'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_4 'a'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_5 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_6 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_7 'u'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_8 'n'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_CORBA_char_struct;
#define TC_CORBA_sequence_CORBA_char ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_char_struct)
#endif
#define CORBA_sequence_CORBA_char__alloc() ((CORBA_sequence_CORBA_char *)ORBit_small_alloc (TC_CORBA_sequence_CORBA_char))
#define CORBA_sequence_CORBA_char__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_CORBA_char,(m),(d))
#define CORBA_sequence_CORBA_char_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_char, (l))
#define CORBA_sequence_CORBA_char_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_char, (l))
#endif
   struct org_pgj_corba_type_value_pair_type
   {
      CORBA_string typename;
      CORBA_sequence_CORBA_char value;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_type_value_pair_0)
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_0 'w'
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_1 'o'
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_2 'r'
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_3 'k'
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_4 'a'
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_5 'r'
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_6 'o'
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_7 'u'
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_8 'n'
#define TC_IMPL_TC_org_pgj_corba_type_value_pair_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_type_value_pair_struct;
#define TC_org_pgj_corba_type_value_pair ((CORBA_TypeCode)&TC_org_pgj_corba_type_value_pair_struct)
#endif
#define org_pgj_corba_type_value_pair__alloc() ((org_pgj_corba_type_value_pair *)ORBit_small_alloc (TC_org_pgj_corba_type_value_pair))
#define org_pgj_corba_type_value_pair__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_type_value_pair,(m),(d))
#endif
#if !defined(_org_pgj_corba_instantiation_type_defined)
#define _org_pgj_corba_instantiation_type_defined 1
   typedef enum
   {
      org_pgj_corba_INSTANTATION_SESSION,
      org_pgj_corba_INSTANTATION_CALL,
      org_pgj_corba_INSTANTATION_GLOBAL
   }
   org_pgj_corba_instantiation_type;
#if !defined(TC_IMPL_TC_org_pgj_corba_instantiation_type_0)
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_0 'w'
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_1 'o'
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_2 'r'
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_3 'k'
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_4 'a'
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_5 'r'
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_6 'o'
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_7 'u'
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_8 'n'
#define TC_IMPL_TC_org_pgj_corba_instantiation_type_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_instantiation_type_struct;
#define TC_org_pgj_corba_instantiation_type ((CORBA_TypeCode)&TC_org_pgj_corba_instantiation_type_struct)
#endif
#endif
#if !defined(_org_pgj_corba_callreq_defined)
#define _org_pgj_corba_callreq_defined 1
   typedef struct org_pgj_corba_callreq_type org_pgj_corba_callreq;
#if !defined(ORBIT_DECL_CORBA_sequence_org_pgj_corba_type_value_pair)
#define ORBIT_DECL_CORBA_sequence_org_pgj_corba_type_value_pair 1
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_0 'w'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_1 'o'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_2 'r'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_3 'k'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_4 'a'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_5 'r'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_6 'o'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_7 'u'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_8 'n'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_9 'd'
#if !defined(_CORBA_sequence_org_pgj_corba_type_value_pair_defined)
#define _CORBA_sequence_org_pgj_corba_type_value_pair_defined 1
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      org_pgj_corba_type_value_pair *_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_org_pgj_corba_type_value_pair;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_0)
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_0 'w'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_1 'o'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_2 'r'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_3 'k'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_4 'a'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_5 'r'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_6 'o'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_7 'u'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_8 'n'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_org_pgj_corba_type_value_pair_struct;
#define TC_CORBA_sequence_org_pgj_corba_type_value_pair ((CORBA_TypeCode)&TC_CORBA_sequence_org_pgj_corba_type_value_pair_struct)
#endif
#define CORBA_sequence_org_pgj_corba_type_value_pair__alloc() ((CORBA_sequence_org_pgj_corba_type_value_pair *)ORBit_small_alloc (TC_CORBA_sequence_org_pgj_corba_type_value_pair))
#define CORBA_sequence_org_pgj_corba_type_value_pair__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_org_pgj_corba_type_value_pair,(m),(d))
#define CORBA_sequence_org_pgj_corba_type_value_pair_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_org_pgj_corba_type_value_pair, (l))
#define CORBA_sequence_org_pgj_corba_type_value_pair_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_org_pgj_corba_type_value_pair, (l))
#endif
   struct org_pgj_corba_callreq_type
   {
      CORBA_string sid;
      CORBA_string classname;
      CORBA_string methodname;
      CORBA_sequence_org_pgj_corba_type_value_pair values;
      CORBA_boolean isoneway;
      org_pgj_corba_instantiation_type instantiation;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_callreq_0)
#define TC_IMPL_TC_org_pgj_corba_callreq_0 'w'
#define TC_IMPL_TC_org_pgj_corba_callreq_1 'o'
#define TC_IMPL_TC_org_pgj_corba_callreq_2 'r'
#define TC_IMPL_TC_org_pgj_corba_callreq_3 'k'
#define TC_IMPL_TC_org_pgj_corba_callreq_4 'a'
#define TC_IMPL_TC_org_pgj_corba_callreq_5 'r'
#define TC_IMPL_TC_org_pgj_corba_callreq_6 'o'
#define TC_IMPL_TC_org_pgj_corba_callreq_7 'u'
#define TC_IMPL_TC_org_pgj_corba_callreq_8 'n'
#define TC_IMPL_TC_org_pgj_corba_callreq_9 'd'
   extern const struct CORBA_TypeCode_struct TC_org_pgj_corba_callreq_struct;
#define TC_org_pgj_corba_callreq ((CORBA_TypeCode)&TC_org_pgj_corba_callreq_struct)
#endif
#define org_pgj_corba_callreq__alloc() ((org_pgj_corba_callreq *)ORBit_small_alloc (TC_org_pgj_corba_callreq))
#define org_pgj_corba_callreq__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_callreq,(m),(d))
#endif
#if !defined(_org_pgj_corba_errorstruct_defined)
#define _org_pgj_corba_errorstruct_defined 1
   typedef struct org_pgj_corba_errorstruct_type org_pgj_corba_errorstruct;
   struct org_pgj_corba_errorstruct_type
   {
      CORBA_string sid;
      CORBA_string classname;
      CORBA_string message;
      CORBA_string stacktrace;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_errorstruct_0)
#define TC_IMPL_TC_org_pgj_corba_errorstruct_0 'w'
#define TC_IMPL_TC_org_pgj_corba_errorstruct_1 'o'
#define TC_IMPL_TC_org_pgj_corba_errorstruct_2 'r'
#define TC_IMPL_TC_org_pgj_corba_errorstruct_3 'k'
#define TC_IMPL_TC_org_pgj_corba_errorstruct_4 'a'
#define TC_IMPL_TC_org_pgj_corba_errorstruct_5 'r'
#define TC_IMPL_TC_org_pgj_corba_errorstruct_6 'o'
#define TC_IMPL_TC_org_pgj_corba_errorstruct_7 'u'
#define TC_IMPL_TC_org_pgj_corba_errorstruct_8 'n'
#define TC_IMPL_TC_org_pgj_corba_errorstruct_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_errorstruct_struct;
#define TC_org_pgj_corba_errorstruct ((CORBA_TypeCode)&TC_org_pgj_corba_errorstruct_struct)
#endif
#define org_pgj_corba_errorstruct__alloc() ((org_pgj_corba_errorstruct *)ORBit_small_alloc (TC_org_pgj_corba_errorstruct))
#define org_pgj_corba_errorstruct__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_errorstruct,(m),(d))
#endif
#define ex_org_pgj_corba_ex_pgj_error "IDL:org/pgj/corba/ex_pgj_error:1.0"
#if !defined(_org_pgj_corba_ex_pgj_error_defined)
#define _org_pgj_corba_ex_pgj_error_defined 1
   typedef struct org_pgj_corba_ex_pgj_error_type org_pgj_corba_ex_pgj_error;
   struct org_pgj_corba_ex_pgj_error_type
   {
      org_pgj_corba_errorstruct exceptiondata;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_ex_pgj_error_0)
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_0 'w'
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_1 'o'
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_2 'r'
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_3 'k'
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_4 'a'
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_5 'r'
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_6 'o'
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_7 'u'
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_8 'n'
#define TC_IMPL_TC_org_pgj_corba_ex_pgj_error_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_ex_pgj_error_struct;
#define TC_org_pgj_corba_ex_pgj_error ((CORBA_TypeCode)&TC_org_pgj_corba_ex_pgj_error_struct)
#endif
#define org_pgj_corba_ex_pgj_error__alloc() ((org_pgj_corba_ex_pgj_error *)ORBit_small_alloc (TC_org_pgj_corba_ex_pgj_error))
#define org_pgj_corba_ex_pgj_error__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_ex_pgj_error,(m),(d))
#endif
#if !defined(_org_pgj_corba_result_defined)
#define _org_pgj_corba_result_defined 1
   typedef struct org_pgj_corba_result_type org_pgj_corba_result;
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_string)
#define ORBIT_DECL_CORBA_sequence_CORBA_string 1
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_0 'w'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_1 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_2 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_3 'k'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_4 'a'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_5 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_6 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_7 'u'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_8 'n'
#define ORBIT_IMPL_CORBA_sequence_CORBA_string_9 'd'
#if !defined(_CORBA_sequence_CORBA_string_defined)
#define _CORBA_sequence_CORBA_string_defined 1
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      CORBA_string *_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_CORBA_string;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_string_0)
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_0 'w'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_1 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_2 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_3 'k'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_4 'a'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_5 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_6 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_7 'u'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_8 'n'
#define TC_IMPL_TC_CORBA_sequence_CORBA_string_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_CORBA_string_struct;
#define TC_CORBA_sequence_CORBA_string ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_string_struct)
#endif
#define CORBA_sequence_CORBA_string__alloc() ((CORBA_sequence_CORBA_string *)ORBit_small_alloc (TC_CORBA_sequence_CORBA_string))
#define CORBA_sequence_CORBA_string__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_CORBA_string,(m),(d))
#define CORBA_sequence_CORBA_string_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_string, (l))
#define CORBA_sequence_CORBA_string_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_string, (l))
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_char)
#define ORBIT_DECL_CORBA_sequence_CORBA_char 1
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_0 'w'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_1 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_2 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_3 'k'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_4 'a'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_5 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_6 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_7 'u'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_8 'n'
#define ORBIT_IMPL_CORBA_sequence_CORBA_char_9 'd'
#if !defined(_CORBA_sequence_CORBA_char_defined)
#define _CORBA_sequence_CORBA_char_defined 1
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      CORBA_char *_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_CORBA_char;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_char_0)
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_0 'w'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_1 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_2 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_3 'k'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_4 'a'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_5 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_6 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_7 'u'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_8 'n'
#define TC_IMPL_TC_CORBA_sequence_CORBA_char_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_CORBA_char_struct;
#define TC_CORBA_sequence_CORBA_char ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_char_struct)
#endif
#define CORBA_sequence_CORBA_char__alloc() ((CORBA_sequence_CORBA_char *)ORBit_small_alloc (TC_CORBA_sequence_CORBA_char))
#define CORBA_sequence_CORBA_char__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_CORBA_char,(m),(d))
#define CORBA_sequence_CORBA_char_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_char, (l))
#define CORBA_sequence_CORBA_char_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_char, (l))
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_sequence_CORBA_char)
#define ORBIT_DECL_CORBA_sequence_CORBA_sequence_CORBA_char 1
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_0 'w'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_1 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_2 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_3 'k'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_4 'a'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_5 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_6 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_7 'u'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_8 'n'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_9 'd'
#if !defined(_CORBA_sequence_CORBA_sequence_CORBA_char_defined)
#define _CORBA_sequence_CORBA_sequence_CORBA_char_defined 1
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      CORBA_sequence_CORBA_char *_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_CORBA_sequence_CORBA_char;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_0)
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_0 'w'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_1 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_2 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_3 'k'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_4 'a'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_5 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_6 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_7 'u'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_8 'n'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_CORBA_char_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_CORBA_sequence_CORBA_char_struct;
#define TC_CORBA_sequence_CORBA_sequence_CORBA_char ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_sequence_CORBA_char_struct)
#endif
#define CORBA_sequence_CORBA_sequence_CORBA_char__alloc() ((CORBA_sequence_CORBA_sequence_CORBA_char *)ORBit_small_alloc (TC_CORBA_sequence_CORBA_sequence_CORBA_char))
#define CORBA_sequence_CORBA_sequence_CORBA_char__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_CORBA_sequence_CORBA_char,(m),(d))
#define CORBA_sequence_CORBA_sequence_CORBA_char_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_sequence_CORBA_char, (l))
#define CORBA_sequence_CORBA_sequence_CORBA_char_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_sequence_CORBA_char, (l))
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_org_pgj_corba_raw)
#define ORBIT_DECL_CORBA_sequence_org_pgj_corba_raw 1
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_0 'w'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_1 'o'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_2 'r'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_3 'k'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_4 'a'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_5 'r'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_6 'o'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_7 'u'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_8 'n'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_raw_9 'd'
#if !defined(_CORBA_sequence_org_pgj_corba_raw_defined)
#define _CORBA_sequence_org_pgj_corba_raw_defined 1
   typedef CORBA_sequence_CORBA_sequence_CORBA_char
      CORBA_sequence_org_pgj_corba_raw;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_0)
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_0 'w'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_1 'o'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_2 'r'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_3 'k'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_4 'a'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_5 'r'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_6 'o'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_7 'u'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_8 'n'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_raw_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_org_pgj_corba_raw_struct;
#define TC_CORBA_sequence_org_pgj_corba_raw ((CORBA_TypeCode)&TC_CORBA_sequence_org_pgj_corba_raw_struct)
#endif
#define CORBA_sequence_org_pgj_corba_raw__alloc CORBA_sequence_CORBA_sequence_CORBA_char__alloc
#define CORBA_sequence_org_pgj_corba_raw__freekids CORBA_sequence_CORBA_sequence_CORBA_char__freekids
#define CORBA_sequence_org_pgj_corba_raw_allocbuf CORBA_sequence_CORBA_sequence_CORBA_char_allocbuf
#define CORBA_sequence_org_pgj_corba_raw_marshal(x,y,z) CORBA_sequence_CORBA_sequence_CORBA_char_marshal((x),(y),(z))
#define CORBA_sequence_org_pgj_corba_raw_demarshal(x,y,z,i) CORBA_sequence_CORBA_sequence_CORBA_char_demarshal((x),(y),(z),(i))
#endif
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw)
#define ORBIT_DECL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw 1
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_0 'w'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_1 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_2 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_3 'k'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_4 'a'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_5 'r'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_6 'o'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_7 'u'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_8 'n'
#define ORBIT_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_9 'd'
#if !defined(_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_defined)
#define _CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_defined 1
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      CORBA_sequence_org_pgj_corba_raw *_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_CORBA_sequence_org_pgj_corba_raw;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_0)
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_0 'w'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_1 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_2 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_3 'k'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_4 'a'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_5 'r'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_6 'o'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_7 'u'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_8 'n'
#define TC_IMPL_TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_struct;
#define TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_struct)
#endif
#define CORBA_sequence_CORBA_sequence_org_pgj_corba_raw__alloc() ((CORBA_sequence_CORBA_sequence_org_pgj_corba_raw *)ORBit_small_alloc (TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw))
#define CORBA_sequence_CORBA_sequence_org_pgj_corba_raw__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw,(m),(d))
#define CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw, (l))
#define CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw, (l))
#endif
   struct org_pgj_corba_result_type
   {
      CORBA_string sid;
      CORBA_sequence_CORBA_string types;
      CORBA_sequence_CORBA_sequence_org_pgj_corba_raw result_tab;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_result_0)
#define TC_IMPL_TC_org_pgj_corba_result_0 'w'
#define TC_IMPL_TC_org_pgj_corba_result_1 'o'
#define TC_IMPL_TC_org_pgj_corba_result_2 'r'
#define TC_IMPL_TC_org_pgj_corba_result_3 'k'
#define TC_IMPL_TC_org_pgj_corba_result_4 'a'
#define TC_IMPL_TC_org_pgj_corba_result_5 'r'
#define TC_IMPL_TC_org_pgj_corba_result_6 'o'
#define TC_IMPL_TC_org_pgj_corba_result_7 'u'
#define TC_IMPL_TC_org_pgj_corba_result_8 'n'
#define TC_IMPL_TC_org_pgj_corba_result_9 'd'
   extern const struct CORBA_TypeCode_struct TC_org_pgj_corba_result_struct;
#define TC_org_pgj_corba_result ((CORBA_TypeCode)&TC_org_pgj_corba_result_struct)
#endif
#define org_pgj_corba_result__alloc() ((org_pgj_corba_result *)ORBit_small_alloc (TC_org_pgj_corba_result))
#define org_pgj_corba_result__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_result,(m),(d))
#endif
#if !defined(_org_pgj_corba_prepared_sql_defined)
#define _org_pgj_corba_prepared_sql_defined 1
   typedef struct org_pgj_corba_prepared_sql_type org_pgj_corba_prepared_sql;
#if !defined(ORBIT_DECL_CORBA_sequence_org_pgj_corba_type_value_pair)
#define ORBIT_DECL_CORBA_sequence_org_pgj_corba_type_value_pair 1
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_0 'w'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_1 'o'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_2 'r'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_3 'k'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_4 'a'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_5 'r'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_6 'o'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_7 'u'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_8 'n'
#define ORBIT_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_9 'd'
#if !defined(_CORBA_sequence_org_pgj_corba_type_value_pair_defined)
#define _CORBA_sequence_org_pgj_corba_type_value_pair_defined 1
   typedef struct
   {
      CORBA_unsigned_long _maximum,
       _length;
      org_pgj_corba_type_value_pair *_buffer;
      CORBA_boolean _release;
   }
   CORBA_sequence_org_pgj_corba_type_value_pair;
#endif
#if !defined(TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_0)
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_0 'w'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_1 'o'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_2 'r'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_3 'k'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_4 'a'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_5 'r'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_6 'o'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_7 'u'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_8 'n'
#define TC_IMPL_TC_CORBA_sequence_org_pgj_corba_type_value_pair_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_CORBA_sequence_org_pgj_corba_type_value_pair_struct;
#define TC_CORBA_sequence_org_pgj_corba_type_value_pair ((CORBA_TypeCode)&TC_CORBA_sequence_org_pgj_corba_type_value_pair_struct)
#endif
#define CORBA_sequence_org_pgj_corba_type_value_pair__alloc() ((CORBA_sequence_org_pgj_corba_type_value_pair *)ORBit_small_alloc (TC_CORBA_sequence_org_pgj_corba_type_value_pair))
#define CORBA_sequence_org_pgj_corba_type_value_pair__freekids(m,d) ORBit_small_freekids (TC_CORBA_sequence_org_pgj_corba_type_value_pair,(m),(d))
#define CORBA_sequence_org_pgj_corba_type_value_pair_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_org_pgj_corba_type_value_pair, (l))
#define CORBA_sequence_org_pgj_corba_type_value_pair_allocbuf(l) ORBit_small_allocbuf (TC_CORBA_sequence_org_pgj_corba_type_value_pair, (l))
#endif
   struct org_pgj_corba_prepared_sql_type
   {
      CORBA_string statement_id;
      CORBA_sequence_org_pgj_corba_type_value_pair data;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_prepared_sql_0)
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_0 'w'
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_1 'o'
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_2 'r'
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_3 'k'
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_4 'a'
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_5 'r'
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_6 'o'
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_7 'u'
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_8 'n'
#define TC_IMPL_TC_org_pgj_corba_prepared_sql_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_prepared_sql_struct;
#define TC_org_pgj_corba_prepared_sql ((CORBA_TypeCode)&TC_org_pgj_corba_prepared_sql_struct)
#endif
#define org_pgj_corba_prepared_sql__alloc() ((org_pgj_corba_prepared_sql *)ORBit_small_alloc (TC_org_pgj_corba_prepared_sql))
#define org_pgj_corba_prepared_sql__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_prepared_sql,(m),(d))
#endif
#if !defined(_org_pgj_corba_simple_sql_defined)
#define _org_pgj_corba_simple_sql_defined 1
   typedef struct org_pgj_corba_simple_sql_type org_pgj_corba_simple_sql;
   struct org_pgj_corba_simple_sql_type
   {
      CORBA_string statement;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_simple_sql_0)
#define TC_IMPL_TC_org_pgj_corba_simple_sql_0 'w'
#define TC_IMPL_TC_org_pgj_corba_simple_sql_1 'o'
#define TC_IMPL_TC_org_pgj_corba_simple_sql_2 'r'
#define TC_IMPL_TC_org_pgj_corba_simple_sql_3 'k'
#define TC_IMPL_TC_org_pgj_corba_simple_sql_4 'a'
#define TC_IMPL_TC_org_pgj_corba_simple_sql_5 'r'
#define TC_IMPL_TC_org_pgj_corba_simple_sql_6 'o'
#define TC_IMPL_TC_org_pgj_corba_simple_sql_7 'u'
#define TC_IMPL_TC_org_pgj_corba_simple_sql_8 'n'
#define TC_IMPL_TC_org_pgj_corba_simple_sql_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_simple_sql_struct;
#define TC_org_pgj_corba_simple_sql ((CORBA_TypeCode)&TC_org_pgj_corba_simple_sql_struct)
#endif
#define org_pgj_corba_simple_sql__alloc() ((org_pgj_corba_simple_sql *)ORBit_small_alloc (TC_org_pgj_corba_simple_sql))
#define org_pgj_corba_simple_sql__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_simple_sql,(m),(d))
#endif
#if !defined(_org_pgj_corba_prepare_defined)
#define _org_pgj_corba_prepare_defined 1
   typedef struct org_pgj_corba_prepare_type org_pgj_corba_prepare;
   struct org_pgj_corba_prepare_type
   {
      CORBA_string statement;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_prepare_0)
#define TC_IMPL_TC_org_pgj_corba_prepare_0 'w'
#define TC_IMPL_TC_org_pgj_corba_prepare_1 'o'
#define TC_IMPL_TC_org_pgj_corba_prepare_2 'r'
#define TC_IMPL_TC_org_pgj_corba_prepare_3 'k'
#define TC_IMPL_TC_org_pgj_corba_prepare_4 'a'
#define TC_IMPL_TC_org_pgj_corba_prepare_5 'r'
#define TC_IMPL_TC_org_pgj_corba_prepare_6 'o'
#define TC_IMPL_TC_org_pgj_corba_prepare_7 'u'
#define TC_IMPL_TC_org_pgj_corba_prepare_8 'n'
#define TC_IMPL_TC_org_pgj_corba_prepare_9 'd'
   extern const struct CORBA_TypeCode_struct TC_org_pgj_corba_prepare_struct;
#define TC_org_pgj_corba_prepare ((CORBA_TypeCode)&TC_org_pgj_corba_prepare_struct)
#endif
#define org_pgj_corba_prepare__alloc() ((org_pgj_corba_prepare *)ORBit_small_alloc (TC_org_pgj_corba_prepare))
#define org_pgj_corba_prepare__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_prepare,(m),(d))
#endif
#if !defined(_org_pgj_corba_cursor_close_defined)
#define _org_pgj_corba_cursor_close_defined 1
   typedef struct org_pgj_corba_cursor_close_type org_pgj_corba_cursor_close;
   struct org_pgj_corba_cursor_close_type
   {
      CORBA_string cursorname;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_cursor_close_0)
#define TC_IMPL_TC_org_pgj_corba_cursor_close_0 'w'
#define TC_IMPL_TC_org_pgj_corba_cursor_close_1 'o'
#define TC_IMPL_TC_org_pgj_corba_cursor_close_2 'r'
#define TC_IMPL_TC_org_pgj_corba_cursor_close_3 'k'
#define TC_IMPL_TC_org_pgj_corba_cursor_close_4 'a'
#define TC_IMPL_TC_org_pgj_corba_cursor_close_5 'r'
#define TC_IMPL_TC_org_pgj_corba_cursor_close_6 'o'
#define TC_IMPL_TC_org_pgj_corba_cursor_close_7 'u'
#define TC_IMPL_TC_org_pgj_corba_cursor_close_8 'n'
#define TC_IMPL_TC_org_pgj_corba_cursor_close_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_cursor_close_struct;
#define TC_org_pgj_corba_cursor_close ((CORBA_TypeCode)&TC_org_pgj_corba_cursor_close_struct)
#endif
#define org_pgj_corba_cursor_close__alloc() ((org_pgj_corba_cursor_close *)ORBit_small_alloc (TC_org_pgj_corba_cursor_close))
#define org_pgj_corba_cursor_close__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_cursor_close,(m),(d))
#endif
#if !defined(_org_pgj_corba_cursor_open_prep_defined)
#define _org_pgj_corba_cursor_open_prep_defined 1
   typedef struct org_pgj_corba_cursor_open_prep_type
      org_pgj_corba_cursor_open_prep;
   struct org_pgj_corba_cursor_open_prep_type
   {
      CORBA_string cursorname;
      org_pgj_corba_prepared_sql prepared;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_cursor_open_prep_0)
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_0 'w'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_1 'o'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_2 'r'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_3 'k'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_4 'a'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_5 'r'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_6 'o'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_7 'u'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_8 'n'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_prep_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_cursor_open_prep_struct;
#define TC_org_pgj_corba_cursor_open_prep ((CORBA_TypeCode)&TC_org_pgj_corba_cursor_open_prep_struct)
#endif
#define org_pgj_corba_cursor_open_prep__alloc() ((org_pgj_corba_cursor_open_prep *)ORBit_small_alloc (TC_org_pgj_corba_cursor_open_prep))
#define org_pgj_corba_cursor_open_prep__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_cursor_open_prep,(m),(d))
#endif
#if !defined(_org_pgj_corba_cursor_open_sql_defined)
#define _org_pgj_corba_cursor_open_sql_defined 1
   typedef struct org_pgj_corba_cursor_open_sql_type
      org_pgj_corba_cursor_open_sql;
   struct org_pgj_corba_cursor_open_sql_type
   {
      CORBA_string cursorname;
      org_pgj_corba_simple_sql sql;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_cursor_open_sql_0)
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_0 'w'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_1 'o'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_2 'r'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_3 'k'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_4 'a'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_5 'r'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_6 'o'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_7 'u'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_8 'n'
#define TC_IMPL_TC_org_pgj_corba_cursor_open_sql_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_cursor_open_sql_struct;
#define TC_org_pgj_corba_cursor_open_sql ((CORBA_TypeCode)&TC_org_pgj_corba_cursor_open_sql_struct)
#endif
#define org_pgj_corba_cursor_open_sql__alloc() ((org_pgj_corba_cursor_open_sql *)ORBit_small_alloc (TC_org_pgj_corba_cursor_open_sql))
#define org_pgj_corba_cursor_open_sql__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_cursor_open_sql,(m),(d))
#endif
#if !defined(_org_pgj_corba_fetch_direction_type_defined)
#define _org_pgj_corba_fetch_direction_type_defined 1
   typedef enum
   {
      org_pgj_corba_FETCH_FORWARD,
      org_pgj_corba_FETCH_BACKWARD
   }
   org_pgj_corba_fetch_direction_type;
#if !defined(TC_IMPL_TC_org_pgj_corba_fetch_direction_type_0)
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_0 'w'
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_1 'o'
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_2 'r'
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_3 'k'
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_4 'a'
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_5 'r'
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_6 'o'
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_7 'u'
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_8 'n'
#define TC_IMPL_TC_org_pgj_corba_fetch_direction_type_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_fetch_direction_type_struct;
#define TC_org_pgj_corba_fetch_direction_type ((CORBA_TypeCode)&TC_org_pgj_corba_fetch_direction_type_struct)
#endif
#endif
#if !defined(_org_pgj_corba_cursor_fetch_defined)
#define _org_pgj_corba_cursor_fetch_defined 1
   typedef struct org_pgj_corba_cursor_fetch_type org_pgj_corba_cursor_fetch;
   struct org_pgj_corba_cursor_fetch_type
   {
      CORBA_string cursorname;
      org_pgj_corba_fetch_direction_type fetch_direction;
      CORBA_long count;
   };

#if !defined(TC_IMPL_TC_org_pgj_corba_cursor_fetch_0)
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_0 'w'
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_1 'o'
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_2 'r'
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_3 'k'
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_4 'a'
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_5 'r'
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_6 'o'
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_7 'u'
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_8 'n'
#define TC_IMPL_TC_org_pgj_corba_cursor_fetch_9 'd'
   extern const struct CORBA_TypeCode_struct
      TC_org_pgj_corba_cursor_fetch_struct;
#define TC_org_pgj_corba_cursor_fetch ((CORBA_TypeCode)&TC_org_pgj_corba_cursor_fetch_struct)
#endif
#define org_pgj_corba_cursor_fetch__alloc() ((org_pgj_corba_cursor_fetch *)ORBit_small_alloc (TC_org_pgj_corba_cursor_fetch))
#define org_pgj_corba_cursor_fetch__freekids(m,d) ORBit_small_freekids (TC_org_pgj_corba_cursor_fetch,(m),(d))
#endif

/** POA structures **/
#ifndef _defined_POA_org_pgj_corba_CallServer
#define _defined_POA_org_pgj_corba_CallServer 1
   typedef struct
   {
      void *_private;
      void (*sendMessage) (PortableServer_Servant _servant,
			   const CORBA_any * message, CORBA_Environment * ev);
      CORBA_any *(*receiveAnsver) (PortableServer_Servant _servant,
				   const CORBA_char * sid,
				   CORBA_Environment * ev);
      CORBA_any *(*SendReceive) (PortableServer_Servant _servant,
				 const CORBA_any * message,
				 CORBA_Environment * ev);
   }
   POA_org_pgj_corba_CallServer__epv;
   typedef struct
   {
      PortableServer_ServantBase__epv *_base_epv;
      POA_org_pgj_corba_CallServer__epv *org_pgj_corba_CallServer_epv;
   }
   POA_org_pgj_corba_CallServer__vepv;
   typedef struct
   {
      void *_private;
      POA_org_pgj_corba_CallServer__vepv *vepv;
   }
   POA_org_pgj_corba_CallServer;
   extern void POA_org_pgj_corba_CallServer__init(PortableServer_Servant
						  servant,
						  CORBA_Environment * ev);
   extern void POA_org_pgj_corba_CallServer__fini(PortableServer_Servant
						  servant,
						  CORBA_Environment * ev);
#endif				/* _defined_POA_org_pgj_corba_CallServer */

/** skel prototypes **/
   void
      _ORBIT_skel_small_org_pgj_corba_CallServer_sendMessage
      (POA_org_pgj_corba_CallServer * _ORBIT_servant, gpointer _ORBIT_retval,
       gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev,
       void (*_impl_sendMessage) (PortableServer_Servant _servant,
				  const CORBA_any * message,
				  CORBA_Environment * ev));
   void
      _ORBIT_skel_small_org_pgj_corba_CallServer_receiveAnsver
      (POA_org_pgj_corba_CallServer * _ORBIT_servant, gpointer _ORBIT_retval,
       gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev,
       CORBA_any * (*_impl_receiveAnsver) (PortableServer_Servant _servant,
					   const CORBA_char * sid,
					   CORBA_Environment * ev));
   void
      _ORBIT_skel_small_org_pgj_corba_CallServer_SendReceive
      (POA_org_pgj_corba_CallServer * _ORBIT_servant, gpointer _ORBIT_retval,
       gpointer * _ORBIT_args, CORBA_Context ctx, CORBA_Environment * ev,
       CORBA_any * (*_impl_SendReceive) (PortableServer_Servant _servant,
					 const CORBA_any * message,
					 CORBA_Environment * ev));

/** stub prototypes **/
   void org_pgj_corba_CallServer_sendMessage(org_pgj_corba_CallServer _obj,
					     const CORBA_any * message,
					     CORBA_Environment * ev);
   CORBA_any *org_pgj_corba_CallServer_receiveAnsver(org_pgj_corba_CallServer
						     _obj,
						     const CORBA_char * sid,
						     CORBA_Environment * ev);
   CORBA_any *org_pgj_corba_CallServer_SendReceive(org_pgj_corba_CallServer
						   _obj,
						   const CORBA_any * message,
						   CORBA_Environment * ev);

/** more internals **/
#if !defined(MARSHAL_IMPL_CORBA_sequence_CORBA_char_0)
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_0 'w'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_1 'o'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_2 'r'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_3 'k'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_4 'a'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_5 'r'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_6 'o'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_7 'u'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_8 'n'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_char_9 'd'
#endif
#if !defined(MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_0)
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_0 'w'
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_1 'o'
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_2 'r'
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_3 'k'
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_4 'a'
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_5 'r'
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_6 'o'
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_7 'u'
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_8 'n'
#define MARSHAL_IMPL_CORBA_sequence_org_pgj_corba_type_value_pair_9 'd'
#endif
#if !defined(MARSHAL_IMPL_CORBA_sequence_CORBA_string_0)
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_0 'w'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_1 'o'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_2 'r'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_3 'k'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_4 'a'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_5 'r'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_6 'o'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_7 'u'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_8 'n'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_string_9 'd'
#endif
#if !defined(MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_0)
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_0 'w'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_1 'o'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_2 'r'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_3 'k'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_4 'a'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_5 'r'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_6 'o'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_7 'u'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_8 'n'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_org_pgj_corba_raw_9 'd'
#endif
#if !defined(MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_0)
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_0 'w'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_1 'o'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_2 'r'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_3 'k'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_4 'a'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_5 'r'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_6 'o'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_7 'u'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_8 'n'
#define MARSHAL_IMPL_CORBA_sequence_CORBA_sequence_CORBA_char_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_type_value_pair_0)
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_type_value_pair_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_callreq_0)
#define MARSHAL_IMPL_org_pgj_corba_callreq_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_callreq_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_callreq_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_callreq_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_callreq_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_callreq_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_callreq_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_callreq_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_callreq_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_callreq_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_errorstruct_0)
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_errorstruct_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_result_0)
#define MARSHAL_IMPL_org_pgj_corba_result_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_result_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_result_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_result_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_result_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_result_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_result_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_result_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_result_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_result_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_prepared_sql_0)
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_prepared_sql_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_simple_sql_0)
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_simple_sql_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_prepare_0)
#define MARSHAL_IMPL_org_pgj_corba_prepare_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_prepare_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_prepare_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_prepare_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_prepare_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_prepare_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_prepare_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_prepare_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_prepare_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_prepare_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_cursor_close_0)
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_cursor_close_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_0)
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_prep_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_0)
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_cursor_open_sql_9 'd'
#endif
#if !defined(MARSHAL_IMPL_org_pgj_corba_cursor_fetch_0)
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_0 'w'
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_1 'o'
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_2 'r'
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_3 'k'
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_4 'a'
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_5 'r'
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_6 'o'
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_7 'u'
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_8 'n'
#define MARSHAL_IMPL_org_pgj_corba_cursor_fetch_9 'd'
#endif
#include <orbit/orb-core/orbit-interface.h>

   extern ORBit_IInterface org_pgj_corba_CallServer__iinterface;
   extern ORBit_IMethod org_pgj_corba_CallServer__imethods[];
#define org_pgj_corba_CallServer_IMETHODS_LEN 3
#ifdef __cplusplus
}
#endif				/* __cplusplus */

#ifndef EXCLUDE_ORBIT_H
#include <orbit/orbit.h>

#endif				/* EXCLUDE_ORBIT_H */
#endif
#undef ORBIT_IDL_SERIAL
